# Generated by Django 5.2 on 2025-04-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type_vehicule', models.CharField(choices=[('voiture', 'Voiture'), ('moto', 'Moto'), ('utilitaire', 'Utilitaire'), ('autre', 'Autre')], max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, help_text='En francs CFA', max_digits=8)),
                ('duree_estimee', models.DurationField(help_text='Exemple: 00:30:00 pour 30 minutes')),
            ],
        ),
    ]
