# Generated by Django 5.2 on 2025-04-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['type_vehicule', 'nom']},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('nom', 'type_vehicule')},
        ),
        migrations.AlterField(
            model_name='service',
            name='duree_estimee',
            field=models.DurationField(help_text='Durée estimée du service, ex: 01:00:00 pour 1 heure'),
        ),
        migrations.AlterField(
            model_name='service',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='service',
            name='type_vehicule',
            field=models.CharField(choices=[('voiture', 'Voiture'), ('moto', 'Moto'), ('tricycle', 'Tricycle'), ('utilitaire', 'Utilitaire'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
    ]
