# Generated by Django 5.2 on 2025-04-30 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options_alter_service_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duree_estimee',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=1800), '30 min'), (datetime.timedelta(seconds=3600), '1h'), (datetime.timedelta(seconds=5400), '1h30'), (datetime.timedelta(seconds=7200), '2h'), (datetime.timedelta(seconds=9000), '2h30'), (datetime.timedelta(seconds=10800), '3h')]),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom',
            field=models.CharField(choices=[('Lavage Intérieur', 'Lavage Intérieur'), ('Lavage Extérieur', 'Lavage Extérieur'), ('Lavage Complet', 'Lavage Complet'), ('Aspiration', 'Aspiration'), ('Désinfection', 'Désinfection')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='prix',
            field=models.PositiveIntegerField(help_text='Prix en francs CFA'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type_vehicule',
            field=models.CharField(choices=[('voiture', 'Voiture'), ('moto', 'Moto'), ('tricycle', 'Tricycle'), ('utilitaire', 'Utilitaire')], max_length=20),
        ),
    ]
