# Generated by Django 5.2 on 2025-04-29 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='nb_roues',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicule',
            name='photo',
            field=models.ImageField(default=4, upload_to='vehicules_photos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type_vehicule',
            field=models.CharField(choices=[('voiture', 'Voiture'), ('moto', 'Moto'), ('tricycle', 'Tricycle'), ('utilitaire', 'Utilitaire'), ('autre', 'Autre')], default='voiture', max_length=20),
        ),
    ]
