# Generated by Django 5.2 on 2025-05-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remove_evaluation_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='temps_reel_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='temps_reel_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
