# Generated by Django 5.2 on 2025-05-01 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_inscription',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
