# Generated by Django 5.2 on 2025-05-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_date_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
