# Generated by Django 5.2 on 2025-05-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_date_inscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_inscription',
        ),
    ]
