# Generated by Django 5.2 on 2025-05-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_points_fidelite_customuser_prime'),
        ('accounts', '0004_remove_customuser_date_inscription'),
    ]

    operations = [
    ]
