# Generated by Django 5.2 on 2025-05-01 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_alter_service_duree_estimee_alter_service_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportPeriodique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('journalier', 'Journalier'), ('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel'), ('annuel', 'Annuel')], max_length=20)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('nombre_reservations', models.PositiveIntegerField()),
                ('revenu_total', models.PositiveIntegerField()),
                ('taux_fidelite', models.FloatField(help_text='Pourcentage de clients récurrents')),
            ],
            options={
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='StatistiqueGenerale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('nombre_reservations', models.PositiveIntegerField(default=0)),
                ('services_realises', models.PositiveIntegerField(default=0)),
                ('revenu_total', models.PositiveIntegerField(default=0)),
                ('nombre_employes', models.PositiveIntegerField(default=0)),
                ('nombre_clients', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistique Générale',
                'verbose_name_plural': 'Statistiques Générales',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_utilisation', models.PositiveIntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'verbose_name': 'Service le plus demandé',
                'verbose_name_plural': 'Services les plus demandés',
                'ordering': ['-nombre_utilisation'],
            },
        ),
    ]
