# Generated by Django 5.2 on 2025-05-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistiques', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RapportPeriodique',
        ),
        migrations.DeleteModel(
            name='ServiceDemande',
        ),
    ]
