# Generated by Django 5.2 on 2025-05-01 21:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistiques', '0002_delete_rapportperiodique_delete_servicedemande'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_realises', models.PositiveIntegerField(default=0)),
                ('note_moyenne', models.FloatField(default=0)),
                ('duree_travail_total', models.DurationField(default=datetime.timedelta(0))),
                ('employe', models.ForeignKey(limit_choices_to={'role': 'employe'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-services_realises'],
            },
        ),
        migrations.CreateModel(
            name='RapportPeriodique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('type_periode', models.CharField(choices=[('journalier', 'Journalier'), ('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel'), ('annuel', 'Annuel')], max_length=20)),
                ('nombre_reservations', models.PositiveIntegerField(default=0)),
                ('nombre_reservations_terminees', models.PositiveIntegerField(default=0)),
                ('nombre_reservations_annulees', models.PositiveIntegerField(default=0)),
                ('revenu_total', models.PositiveIntegerField(default=0, help_text='Revenu en francs CFA')),
                ('nombre_employes_actifs', models.PositiveIntegerField(default=0)),
                ('nombre_clients_actifs', models.PositiveIntegerField(default=0)),
                ('taux_occupation', models.FloatField(default=0, help_text="Pourcentage d'occupation des employés")),
                ('note_moyenne', models.FloatField(default=0, help_text='Note moyenne des évaluations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ServicePopularite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.PositiveIntegerField()),
                ('service_nom', models.CharField(max_length=50)),
                ('service_type_vehicule', models.CharField(max_length=20)),
                ('nombre_reservations', models.PositiveIntegerField(default=0)),
                ('pourcentage', models.FloatField(default=0, help_text='Pourcentage du total des réservations')),
                ('revenu_genere', models.PositiveIntegerField(default=0, help_text='Revenu en francs CFA')),
            ],
            options={
                'ordering': ['-nombre_reservations'],
            },
        ),
        migrations.DeleteModel(
            name='StatistiqueGenerale',
        ),
        migrations.AddIndex(
            model_name='rapportperiodique',
            index=models.Index(fields=['type_periode', 'date_debut'], name='statistique_type_pe_d136bd_idx'),
        ),
        migrations.AddField(
            model_name='performanceemploye',
            name='rapport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances_employes', to='statistiques.rapportperiodique'),
        ),
        migrations.AddField(
            model_name='servicepopularite',
            name='rapport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_popularite', to='statistiques.rapportperiodique'),
        ),
    ]
